[metadata]
name = admit14_camera
version = 0.1.0
author = Admit14
author_email = maintainer@example.com
maintainer = Admit14
maintainer_email = maintainer@example.com
description = Camera publishers and viewers used in the Admit 14 ROS 2 labs
license = Apache-2.0

[options]
packages = find:
install_requires =
    setuptools
    rclpy
    opencv-python
    numpy
    ultralytics
zip_safe = false

[options.entry_points]
console_scripts =
    gstreamer_camera_publisher = admit14_camera.gstreamer_camera_publisher:main
    windows_camera_publisher = admit14_camera.windows_camera_publisher:main
    windows_camera_viewer = admit14_camera.windows_camera_viewer:main
    windows_yolo_viewer = admit14_camera.windows_yolo_viewer:main
    stereo_yolo_viewer = admit14_camera.stereo_yolo_viewer:main
    left_eye_yolo_viewer = admit14_camera.mono_yolo_viewers:main_left
    right_eye_yolo_viewer = admit14_camera.mono_yolo_viewers:main_right
